"""create voice_messages table

Revision ID: f99f593582bd
Revises: 
Create Date: 2024-12-10 10:49:26.140948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99f593582bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('voice_url', sa.String(), nullable=False),
    sa.Column('recognized_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_messages_id'), 'voice_messages', ['id'], unique=False)
    op.create_index(op.f('ix_voice_messages_user_id'), 'voice_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_messages_user_id'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_id'), table_name='voice_messages')
    op.drop_table('voice_messages')
    # ### end Alembic commands ###
