name: verified

on:
  push:
    branches:
      - wip
      - main
  pull_request:


jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Установка зависимостей
        run: |
          pip install flake8==7.1.1 mypy==1.13.0

      - name: Запуск Flake8
        run: flake8 .

      - name: Запуск Mypy
        run: mypy .
